name: unbound_ci

on:
  pull_request:
    types: closed
    branches: master
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and load
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: hferreira/unbound:latest
      -
        name: Scan container
        id: scan
        uses: anchore/scan-action@v6
        with:
          image: "hferreira/unbound:latest"
          fail-build: true
          by-cve: true
          severity-cutoff: high
          output-format: sarif
      - 
        name: Upload SARIF file
        id: upload_sarif
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hferreira/unbound:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_push.outputs.digest }}
